### ISSUE TITLE
[GTPU] tunnel_gtpu controller

### ISSUE THREAD

**Issue by GinesGarcia** [lagopus/ryu-lagopus-ext#1]
Hi,
I'm trying set up a controller for GTP-U traffic but when running ``ryu-manager tunnel_gtpu.py`` I'm facing with the following error:
``TunnelGTPU: Exception occurred during handler processing. Backtrace from offending handler [switch_features_handler] servicing event [EventOFPSwitchFeatures] follows.
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/user/ryu-lagopus-ext/ryu/app/tunnel_gtpu.py", line 21, in switch_features_handler
    type_eth  = (ofp.OFPHTN_ONF << 16) | ofp.OFPHTO_ETHERNET
AttributeError: 'module' object has no attribute 'OFPHTN_ONF'``

EDIT: ``OFPHTN_ONF`` is defined in ofproto_v1_5.py but this controller is using ofproto_v1_3.py and that is why the needed attribute is not found.

Any suggestion about how to handle this situation?

Regards,
Ginés.

**Comment by iMasaruOki** [comment]
Currently, Lagopus tunnel support is not used ONF standard match/action.
Try https://github.com/lagopus/ryu-lagopus-ext instead of original Ryu.

Thank you.

**Comment by Qain0130** [comment]
Hi ,
I try  https://github.com/lagopus/ryu-lagopus-ext instead of original Ryu.

but still Encounter the same problems

How to solve about this problem?

**Comment by hibitomo** [comment]
We defined `OFPHTN_ONF` in `ryu/ofproto/ofproto_v1_3.py`.
https://github.com/lagopus/ryu-lagopus-ext/blob/lagopus-general-tunnel-ext/ryu/ofproto/ofproto_v1_3.py#L809-L824

Your ryu application may be running with original ryu-manager.
Please try re-installing ryu of `ryu-lagopus-ext` branch.

Thank you.
